config/routes.rb
RedditClone::Application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create, :destroy, :edit, :show]
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true
  belongs_to(
    :sub,
    :inverse_of => :posts
  )

  belongs_to(
    :author,
    :class_name => "User",
    :foreign_key => :author_id,
    :primary_key => :id,
    :inverse_of => :posts
  )

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :moderator_id, :description, presence: true
  has_many(
    :posts,
    :class_name => "Post",
    foreign_key: :sub_id,
    primary_key: :id,
    inverse_of: :sub
  )
  belongs_to(
    :moderator,
    :class_name => "User",
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :subs
  )
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
  include BCrypt
  validates :username, :session_token, :password_digest, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :set_session_token

  has_many(
    :subs,
    :class_name => "Sub",
    :foreign_key => :moderator_id,
    :primary_key => :id,
    :inverse_of => :moderator
  )
  has_many(
  :posts,
  :class_name => "Post",
  :foreign_key => :author_id,
  :primary_key => :id,
  :inverse_of => :author
  )
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def password
    @password
  end

  def password_is?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def set_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    return current_user.nil? ? false : true
  end

  def find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user
      if user.password_is?(password)
        return user
      end
    end

    nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    render :new
  end

  def create
    author_params = {:author_id => current_user.id}
    new_params = post_params.merge({:sub_id => params[:sub_id]})
    new_params = new_params.merge(author_params)
    @post = Post.new(new_params)
    if @post.save
      redirect_to sub_url(@post.sub)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = Post.find(params[id]).destroy
    redirect_to sub_url(@post.sub)
  end

  def edit
    @post = Post.find(params[id])
    render :edit
  end

  def show
    @post = Post.find(params[id])
    render :show
  end

  private
  def post_params
    params.require(:post).permit(:url, :title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    username = session_params[:username]
    password = session_params[:password]
    @user = User.new(session_params)
    @current_user = find_by_credentials(username, password)
    if @current_user
      self.login(@current_user)
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = "invalid username or password"
      render :new
    end
  end

  def destroy
    self.logout
    redirect_to new_session_url
  end

  private
  def session_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    render :index
  end
  def show
    @sub = Sub.find(params[:id])
    render :show
  end
  def create
    new_params = {"moderator_id" => current_user.id}.merge(sub_params)
    @sub = Sub.new(new_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    render :index
  end
  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end
  def update
    new_params = {"moderator_id" => current_user.id}.merge(sub_params)
    @sub = Sub.new(new_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  def new
    @sub = Sub.new
    render :new
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def destroy
  end

  def edit
    render :edit
  end

  def update
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:errors] %>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<h1> make a post </h1>
<form action="<%= sub_posts_url %>" method="POST">
  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">

    <label for="post_title"> Tittle of poost </label>
  <input type="text" name="post[title]" id="post_title"
  value="<%= @post.title %>">

    <label for="post_content"> Post Content </label>
  <textarea rows="20" columns="30" name="post[content]"
   id="post_content" value="<%= @post.content %>"></textarea>

     <label for="post_url"> Liiink </label>
   <input type="text" name="post[url]" id="post_url"
   value="<%= @post.url %>">

   <input type="submit" value="submit">

</form>

app/views/subs/edit.html.erb
<h1>Edit Sub </h1>


<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">

    <label for="sub_title"> Tittle of sub </label>
  <input type="text" name="sub[title]" id="sub_title"
  value="<%= @sub.title %>">

    <label for="sub_description"> Sub description </label>
  <input type="text_area" rows="20" columns="30" name="sub[description]"
   id="sub_description" value="<%= @sub.description %>">

   <input type="submit" value="submit">

</form>

app/views/subs/index.html.erb
<h1>All subs</h1>
<ul>
<% Sub.all.each do |sub| %>
    <li>
      <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
      <form action="<%= sub_url(sub) %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token"
        value="<%= form_authenticity_token %>">

        <input type="submit" value="delete" name="submit">
      </form>
    </li>
<% end %>
</ul>

<form action="<%=new_sub_url%>" method="GET">
  <input type="submit" value="make a new sub" name="submit">
  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">
</form>

app/views/subs/new.html.erb
<h1> New Sub </h1>


<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">

    <label for="sub_title"> Tittle of sub </label>
  <input type="text" name="sub[title]" id="sub_title"
  value="<%= @sub.title %>">

    <label for="sub_description"> Sub description </label>
  <textarea rows="20" columns="30" name="sub[description]"
   id="sub_description" value="<%= @sub.description %>"></textarea>

   <input type="submit" value="submit">

</form>

app/views/subs/show.html.erb
<h1> Welcome to the Page for <%= @sub.title%>!!!!! </h1>
Descriytion : <%= @sub.description %> <br>
Moderayyytor : <%= @sub.moderator.username %>
<ol>
Poooosts: <% @sub.posts.each do |post| %>
  <li> <%= post.title %> </li>
  <form action="<%= sub_post_url(post) %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <input type="submit" value="delete" name="submit">
  </form>
<% end %>
</ol>

<a href="<%= edit_sub_url(@sub) %>"> Edit Sub </a> <br>
<a href="<%= new_sub_post_url(@sub) %>"> New Post </a>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<form action="<%= users_url %>" method="POST">
<input
name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
<p>
<label for="username"> Username </label>
<input type="text" id="username" name="user[username]"
value="<%= @user.username %>">
</p>
<p>
<label for="password"> Password </label>
<input type="password" id="password" name="user[password]">
</p><br>
<input type="submit" name="submit" value="submit">


</form>

app/views/users/show.html.erb
<h1> Welcome! <%= @user.username %> </h1>

<form action="<%= session_url %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="submit" value="Log Out">
</form>